name: Build and Publish

on:
  push:
  workflow_dispatch:

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env_to_promote_to }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "15.5"
      - name: Install dependencies
        run: yarn
      - name: Build ssr
        run: yarn run build
      - name: build and push image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PWD }}
          repository: hot55797700/ssr-test
          dockerfile: Dockerfile
          tags: latest
      - name: build and push api image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PWD }}
          repository: hot55797700/api-test
          dockerfile: api.dockerfile
          tags: latest
      - name: Just echo
        run: echo "Workflow end"

  test-services:
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest
    services:
      api:
        image: hot55797700/api-test
        env:
          PORT: 9001
        ports:
          - 9001:9001
      ssr:
        image: hot55797700/ssr-test
        env:
          API_SERVER_HOST: api
          API_SERVER_PORT: 9001
        ports:
          - 3000:3000
    steps:
      - name: check-ssr-response
        run: curl "http://localhost:3000"
      - name: check-api-response
        run: curl "http://localhost:9001/time"
